[package]
name = "krpc_encoding"
version = "0.1.0"
authors = ["Martin Charles <martincharles07@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.79"
serde_derive = "1.0.79"
serde_bencode = { git = "https://github.com/0xcaff/serde-bencode.git", rev = "0c1e6f4672c925c629b84fab2b66b24ec9f3458e" }
serde_bytes = "0.10.4"
failure = "0.1.2"
failure_derive = "0.1.2"
byteorder = "1.2.6"
rand = "0.8.5"
hex = "0.4.3"
num-bigint = "0.4.3"
num-traits = "0.2.6"

[dev-dependencies]
serde_test = "1.0.79"
