[package]
name = "tokio_krpc"
version = "0.1.0"
authors = ["Martin Charles <martincharles07@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.6"
bytes = "0.4.10"
rand = "0.5.5"
failure = "0.1.2"
failure_derive = "0.1.2"
tokio = { git = "https://github.com/tokio-rs/tokio.git", branch = "master" }
futures-preview = "0.3.0-alpha.17"
futures-util-preview = "0.3.0-alpha.17"
krpc_encoding = { path = "../krpc_encoding" }
