[package]
name = "tokio_krpc"
version = "0.1.0"
authors = ["Martin Charles <martincharles07@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.6"
bytes = "0.4.10"
rand = "0.5.5"
failure = "0.1.2"
failure_derive = "0.1.2"
tokio = { version = "1.23.0", features = ["net"] }
futures = "0.3.25"
futures-util = "0.3.25"
krpc_encoding = { path = "../krpc_encoding" }

[dev-dependencies]
tokio = { version = "1.23.0", features = ["net", "macros", "rt"] }
